(function(){
  const c=window.LOCAL_OPS_CONFIG;
  document.documentElement.style.setProperty('--brand',c.brand);
  document.documentElement.style.setProperty('--brand2',c.brand2);
  const rows=c.queue.map((r,i)=>`<article class="item" data-status="${r.status}"><span class="signal"></span><div><b>${r.title}</b><div class="meta">${r.meta}</div></div><span class="owner">${r.owner}</span></article>`).join('');
  const metrics=c.metrics.map(m=>`<div class="metric"><b>${m.value}</b><span>${m.label}</span></div>`).join('');
  const steps=c.steps.map((s,i)=>`<div class="step"><span>0${i+1}</span><b>${s}</b></div>`).join('');
  document.getElementById('app').innerHTML=`<div class="shell"><header class="top"><div class="brand">${c.company} / OPERATIONS CONCEPT</div><div class="badge">Private concept demo · no live customer data</div></header><section class="hero"><div class="hero-main"><div class="eyebrow">${c.kicker}</div><h1>${c.headline}</h1><p>${c.summary}</p></div><aside class="hero-side"><div><h2>Fixed implementation scope</h2><ul>${c.scope.map(x=>`<li><strong>${x.title}</strong>${x.text}</li>`).join('')}</ul></div><div class="price">$${c.price.toLocaleString()}<small>${c.delivery} · subject to workflow confirmation</small></div></aside></section><section class="grid"><div class="panel"><div class="panel-head"><h2>Callback & opportunity queue</h2><div class="filters"><button class="filter active" data-filter="all">All</button><button class="filter" data-filter="overdue">Overdue</button><button class="filter" data-filter="new">New</button></div></div><div class="queue">${rows}</div></div><aside class="panel"><div class="panel-head"><h2>Modeled view</h2></div><div class="metrics">${metrics}</div><div class="truth">Illustrative workflow data only. These figures are not claims about ${c.company}. The implementation begins with a redacted export and agreed acceptance rules.</div></aside></section><section class="panel flow"><div class="panel-head"><h2>What changes after implementation</h2></div><div class="steps">${steps}</div></section><section class="cta"><div><h2>Start with one redacted workflow sample.</h2><p>No passwords by email. No CRM replacement. No automated dispatch until the exception layer is accepted.</p></div><a href="mailto:forevercrab321@gmail.com?subject=${encodeURIComponent(c.company+' workflow scope')}">Confirm the scope</a></section></div>`;
  document.querySelectorAll('.filter').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));button.classList.add('active');const f=button.dataset.filter;document.querySelectorAll('.item').forEach(item=>item.hidden=f!=='all'&&item.dataset.status!==f)}));
})();
